version: 2

sources:
  - name: raw
    description: Raw Jaffle Shop data
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: Raw customer data from Jaffle Shop
        columns:
          - name: id
            description: Customer ID
          - name: first_name
            description: Customer first name
          - name: last_name
            description: Customer last name

      - name: orders
        description: Raw orders data from Jaffle Shop
        columns:
          - name: id
            description: Order ID
          - name: user_id
            description: Customer ID
          - name: order_date
            description: Date order was placed
          - name: status
            description: Order status

  - name: stripe
    description: Raw payment data from Stripe
    database: raw
    schema: stripe
    tables:
      - name: payment
        description: Raw payment data from Stripe
        columns:
          - name: id
            description: Payment ID
          - name: orderid
            description: Order ID
          - name: paymentmethod
            description: Payment method used
          - name: status
            description: Payment status
          - name: amount
            description: Payment amount in cents
          - name: created
            description: Payment creation date
